### Email history by email
GET localhost:8080/api/v1/email-history/by-email?email=javqochdiyev@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJlc2htYXQ1QGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDVAZ21haWwuY29tIiwiaWF0IjoxNzgxNDk5MjczLCJleHAiOjE3ODE1ODU2NzN9.gJfI8xp5AuiV3xfwL0yExlySLQtmSQSDmvfpE52VPvwWOSL72yieXdNdXPG8rpAh31odZdJnpOUqroWVcL7o4g

### Email history by date
GET localhost:8080/api/v1/email-history/by-date?date=2026-06-15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJlc2htYXQ1QGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDVAZ21haWwuY29tIiwiaWF0IjoxNzgxNDk5MjczLCJleHAiOjE3ODE1ODU2NzN9.gJfI8xp5AuiV3xfwL0yExlySLQtmSQSDmvfpE52VPvwWOSL72yieXdNdXPG8rpAh31odZdJnpOUqroWVcL7o4g

### Email history pagination
GET localhost:8080/api/v1/email-history/pagination?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJlc2htYXQ1QGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDVAZ21haWwuY29tIiwiaWF0IjoxNzgxNDk5MjczLCJleHAiOjE3ODE1ODU2NzN9.gJfI8xp5AuiV3xfwL0yExlySLQtmSQSDmvfpE52VPvwWOSL72yieXdNdXPG8rpAh31odZdJnpOUqroWVcL7o4g

