### Maqolani saqlash / o'chirish
POST localhost:8080/api/v1/saved-article/f927e615-e4fa-4fb2-b00e-934c436d5e3f
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJlc2htYXQ1QGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDVAZ21haWwuY29tIiwiaWF0IjoxNzgxNzg0ODA2LCJleHAiOjE3ODE4NzEyMDZ9.2oVDq_nkCSs0qAorCD9AN2CZw-EGtnZkrhgxTYKSuUl_euHhWanJse65wOjNku3zZ_4asCk3nT5Vl6Lz1-hVww

### Saqlangan maqolalarni olish
GET localhost:8080/api/v1/saved-article?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJlc2htYXQ1QGdtYWlsLmNvbSIsInN1YiI6ImVzaG1hdDVAZ21haWwuY29tIiwiaWF0IjoxNzgxNzg0ODA2LCJleHAiOjE3ODE4NzEyMDZ9.2oVDq_nkCSs0qAorCD9AN2CZw-EGtnZkrhgxTYKSuUl_euHhWanJse65wOjNku3zZ_4asCk3nT5Vl6Lz1-hVww
